import requests
import time
import os
import json
import logging
import sys
from datetime import datetime
from google import genai
from ddgs import DDGS

# --- Logging Setup ---
class JsonFormatter(logging.Formatter):
    def format(self, record):
        log_record = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "level": record.levelname,
            "component": "skill.daily-brief",
            "message": record.getMessage(),
        }
        return json.dumps(log_record)

logger = logging.getLogger("daily-brief")
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(JsonFormatter())
logger.addHandler(handler)
logger.setLevel(logging.INFO)
# ---------------------

# Configuration
SIDECAR_URL = os.getenv("SIDECAR_URL", "http://127.0.0.1:12345")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

def search_news(topic="Technology"):
    logger.info(f"Searching news for topic: {topic}...")
    
    if not GOOGLE_API_KEY:
        logger.warning("GOOGLE_API_KEY not found. Using Mock Data.")
        # Mock search results
        time.sleep(1)
        return [
            {"title": "AI Revolutionizes Local Productivity", "source": "TechDaily", "body": "New tools allow local AI execution..."},
            {"title": "Docker Containers for Everyone", "source": "DevNews", "body": "Simplifying container orchestration..."}
        ]

    try:
        results = DDGS().text(f"{topic} news", max_results=3)
        logger.info(f"Found {len(results)} articles.")
        return results
    except Exception as e:
        logger.error(f"Search failed: {e}. Falling back to mock.")
        return [
            {"title": "AI Revolutionizes Local Productivity", "body": "Mock body due to search failure."}
        ]

def summarize_news(articles):
    logger.info("Summarizing articles...")
    
    if not GOOGLE_API_KEY:
        logger.warning("Using Mock Summarization.")
        time.sleep(1)
        summary = "# Daily Brief (Mock)\n\n"
        for art in articles:
            summary += f"## {art.get('title')}\n"
            summary += f"{art.get('body', '')[:100]}...\n\n"
        summary += "---\nGenerated by Contex Brain (Mock)"
        return summary

    try:
        client = genai.Client(api_key=GOOGLE_API_KEY)
        
        prompt = "Summarize the following news articles into a daily brief markdown format:\n\n"
        for art in articles:
            prompt += f"Title: {art.get('title')}\nContent: {art.get('body', '')}\n\n"
            
        response = client.models.generate_content(
            model='gemini-2.0-flash',
            contents=prompt
        )
        logger.info("Summarization complete.")
        return response.text
    except Exception as e:
        logger.error(f"AI Summarization failed: {e}")
        return "# Daily Brief (Error)\nFailed to generate summary."

def notify_sidecar(content):
    logger.info("Sending brief to Sidecar...")
    try:
        payload = {"title": "Daily News Brief", "content": content}
        resp = requests.post(f"{SIDECAR_URL}/notify", json=payload)
        resp.raise_for_status()
        logger.info("Notification sent successfully!")
    except Exception as e:
        logger.error(f"Failed to notify Sidecar: {e}")

def run():
    logger.info("=== Starting Daily Brief Agent ===")
    try:
        articles = search_news()
        summary = summarize_news(articles)
        notify_sidecar(summary)
        logger.info("=== Task Completed ===")
    except Exception as e:
        logger.critical(f"Agent failed with unhandled exception: {e}")
        sys.exit(1)

if __name__ == "__main__":
    run()
